name = "Gaussian_Clock_Cluster"
uuid = "206d260b-fbd1-4e07-9fcc-2090f4e1cfd9"
authors = ["Ayush De <ayush.de9@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
